spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hupi
    username: root
    password: mmaawwww111

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名与下划线命名自动转换